import csv
import json
from collections import defaultdict
import os

def convert_csv_abaqus_to_json(path_csv, path_json, main_key, name_field_data):
    """
    Convert CSV files from paths of Abaqus containing multiple frames
    for the customized JSON dictionary structure.
    
    Parameters:
    -----------
    path_csv : str
        Complete path of the CSV file generated by Abaqus.
    path_json : str
        Path where the structured JSON file will be saved.
    main_key : str
        Name of the main node in the JSON (e.g., 'rock_displacement', 'casing_stress').
    name_field_data : str
        Name of the temporal data dictionary (e.g., 'time_displacements', 'time_stresses').
    """
    if not os.path.exists(path_csv):
        print(f"Warning: File {path_csv} not found. Skipping...")
        return False

    node_to_z = {}
    data_by_time = defaultdict(dict)
    nodes_order = []

    # 1. Reading and dynamic grouping of the data
    with open(path_csv, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader)  # Ignores the header line of the Abaqus file
        
        for row in reader:
            if not row or len(row) < 4: 
                continue
                
            try:
                time_str = row[0].strip()
                node = int(row[1])
                z_pos = float(row[2])
                value = float(row[3]) # Can be displacement, stress, etc.
                
                # Registers the node and its geometric Z coordinate only once
                if node not in node_to_z:
                    node_to_z[node] = z_pos
                    nodes_order.append(node)
                
                # Stores the value indexed by time and node
                data_by_time[time_str][node] = value
                
            except ValueError:
                continue

    # 2. Construction of coordinate vectors
    z_coords = [node_to_z[n] for n in nodes_order]

    # 3. Construction of time series aligned with the node order
    time_series_dict = {}
    for t_str, nodes_dict in data_by_time.items():
        values_aligned = [nodes_dict.get(n, 0.0) for n in nodes_order]
        time_series_dict[t_str] = values_aligned

    # 4. Assembly of the dynamic JSON structure
    structure_json = {
        main_key: {
            "node_labels": nodes_order,
            "z_coords": z_coords,
            name_field_data: time_series_dict
        }
    }

    # 5. Saving the final file
    with open(path_json, 'w', encoding='utf-8') as f:
        json.dump(structure_json, f, indent=4)
        
    print(f"Success: '{path_csv}' converted to '{path_json}'.")
    return True